name: listen to issues
on:
  issues:
    types: [opened, edited, deleted]
jobs:
  issue-listener:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue event details
        run: |
                echo "${{ toJSON(github.event.action) }} "
                echo "${{ toJSON(github.event.issue) }} "   